import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

void main() => runApp(const RunnerApp());
class RunnerApp extends StatelessWidget { const RunnerApp({super.key}); @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner:false,title:'Subway Offline MOD',theme:ThemeData.dark(useMaterial3:true),home:const GamePage()); }
class GamePage extends StatefulWidget { const GamePage({super.key}); @override State<GamePage> createState()=>_GamePageState(); }
class _GamePageState extends State<GamePage>{ final rng=Random(); Timer? timer; int lane=1,score=0,coins=999999,multiplier=100; bool running=false,mod=true,jumping=false; double world=0; List<Thing> things=[]; @override void dispose(){timer?.cancel();super.dispose();} void start(){score=0;lane=1;world=0;things.clear();running=true;timer?.cancel();timer=Timer.periodic(const Duration(milliseconds:16),(_)=>tick());setState((){});} void tick(){if(!running)return;world+=.012;score+=mod?multiplier:1;if(rng.nextDouble()<.025)things.add(Thing(rng.nextInt(3),1.12,rng.nextDouble()<.72));for(final t in things){t.y-=.012;}for(final t in things.where((e)=>!e.hit&&e.y>.78&&e.y<.92&&e.lane==lane)){t.hit=true;if(t.coin){coins+=mod?100:1;score+=mod?5000:100;}else if(!mod&&!jumping){running=false;timer?.cancel();}}things.removeWhere((e)=>e.y<-.1);if(mounted)setState((){});} void move(int d)=>setState(()=>lane=(lane+d).clamp(0,2)); void jump(){if(jumping)return;setState(()=>jumping=true);Future.delayed(const Duration(milliseconds:650),(){if(mounted)setState(()=>jumping=false);});}
@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:GestureDetector(onHorizontalDragEnd:(d)=>move((d.primaryVelocity??0)<0?1:-1),onVerticalDragEnd:(d){if((d.primaryVelocity??0)<0)jump();},child:Stack(children:[Positioned.fill(child:CustomPaint(painter:GamePainter(lane,world,things,jumping))),Positioned(top:12,left:12,right:12,child:Row(children:[stat('SCORE','$score'),const Spacer(),stat('MOEDAS','$coins'),const SizedBox(width:8),FilterChip(label:Text(mod?'MOD ON':'MOD OFF'),selected:mod,onSelected:(v)=>setState(()=>mod=v))])),if(!running)Center(child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Image.asset('assets/original/+18.png',height:70,errorBuilder:(_,__,___)=>const SizedBox()),const Text('RUNNER OFFLINE',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(mod?'MOD: invencível • moedas x100 • score x$multiplier':'Modo normal'),const SizedBox(height:18),FilledButton.icon(onPressed:start,icon:const Icon(Icons.play_arrow),label:const Text('JOGAR'))])))),Positioned(bottom:18,left:16,right:16,child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[FilledButton.tonal(onPressed:()=>move(-1),child:const Icon(Icons.arrow_left)),FilledButton.tonal(onPressed:jump,child:const Icon(Icons.arrow_upward)),FilledButton.tonal(onPressed:()=>move(1),child:const Icon(Icons.arrow_right))]))])))); Widget stat(String a,String b)=>Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(12)),child:Column(children:[Text(a,style:const TextStyle(fontSize:10)),Text(b,style:const TextStyle(fontWeight:FontWeight.bold))]));}
class Thing{Thing(this.lane,this.y,this.coin);int lane;double y;bool coin;bool hit=false;}
class GamePainter extends CustomPainter{GamePainter(this.lane,this.world,this.things,this.jumping);final int lane;final double world;final List<Thing> things;final bool jumping;@override void paint(Canvas c,Size s){c.drawRect(Offset.zero&s,Paint()..color=const Color(0xff159bd3));final city=Paint()..color=const Color(0xff294e72);for(int i=0;i<8;i++){final w=s.width/8,h=80.0+(i%3)*45;c.drawRect(Rect.fromLTWH(i*w,s.height*.18-h/2,w-3,h),city);}final road=Path()..moveTo(s.width*.25,s.height*.28)..lineTo(s.width*.75,s.height*.28)..lineTo(s.width,s.height)..lineTo(0,s.height)..close();c.drawPath(road,Paint()..color=const Color(0xff33383e));for(final t in things){final p=perspective(t.lane,t.y,s),r=8+30*t.y;c.drawCircle(p,r,Paint()..color=t.coin?Colors.amber:Colors.redAccent);}final px=[s.width*.30,s.width*.50,s.width*.70][lane],py=s.height*(jumping?.70:.82);c.drawCircle(Offset(px,py-30),16,Paint()..color=Colors.orangeAccent);c.drawRRect(RRect.fromRectAndRadius(Rect.fromCenter(center:Offset(px,py),width:38,height:58),const Radius.circular(10)),Paint()..color=Colors.blueAccent);}Offset perspective(int lane,double y,Size s){final near=[.30,.50,.70][lane],far=[.43,.50,.57][lane],x=far+(near-far)*y;return Offset(s.width*x,s.height*(.28+.72*y));}@override bool shouldRepaint(covariant GamePainter oldDelegate)=>true;}
